#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2       # Number of CPUs
#SBATCH --mem-per-cpu=5G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK

# rungms JOB VERNO NCPUS >& JOB.log
/home/bjb2chen/gamess/rungms nh3_ccd_Sint_ats0g.inp 00 2 &> step3_may23_nh3_ccd_Sint_ats0g.log
