#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2       # Number of CPUs
#SBATCH --mem-per-cpu=5G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK

# rungms JOB VERNO NCPUS >& JOB.log
/home/bjb2chen/gamess/rungms nh3cat_ccd_gmcpt_7o7e_C3vinC1_3st_diab.inp 00 2 &> step5_may23_nh3cat_ccd_gmcpt_7o7e_C3vinC1_3st_diab.log
