#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2       # Number of CPUs
#SBATCH --mem-per-cpu=40G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK
mkdir -p /home/$USER/.gamess_ascii_files/$SLURM_JOBID

# rungms JOB VERNO NCPUS >& JOB.log
/home/bjb2chen/gamess/rungms ph3_cct_mp2_D3h_gh.inp 00 2 &> step1_ph3_cct_mp2_D3h_gh.log
sleep 10
cp /home/$USER/.gamess_ascii_files/$SLURM_JOBID/* .
