#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2       # Number of CPUs
#SBATCH --mem-per-cpu=5G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK
mkdir -p /home/$USER/.gamess_ascii_files/$SLURM_JOBID

# rungms JOB VERNO NCPUS >& JOB.log
# step 1: MP2 geometry optimization and frequency calculations for netural molecule
#/home/bjb2chen/gamess/rungms h2o_cct_mp2_c2v_gh.inp 00 2 &> h2o_cct_mp2_c2v_gh.log
# step 2: MC-PT calculation for excited states at the optimized geometry and one 1 electron ionization  
#/home/bjb2chen/gamess/rungms h2ocat_cct_gmcpt_6o7e_C2vinC1_3st.inp 00 2 &> h2ocat_cct_gmcpt_6o7e_C2vinC1_3st.log
# step 3: expressed adiabatic states in diabatic moleculear orbitals (DMOs) and prepare reference multi-slater determinant states for diabatization
#/home/bjb2chen/gamess/rungms h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_dmo.inp 00 2 &> h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_dmo.log
#step 4: Diabatization at original geometry
#/home/bjb2chen/gamess/rungms h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_diab.inp 00 2 &> h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_diab.log
#step 5: Diabatization at displaced geometry
#/home/bjb2chen/gamess/rungms h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_diab_Ox_plus_0.1.inp 00 2 &> h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_diab_Ox_plus_0.1.log
#step 5: creat a grid on distorted structures along one normal mode and conduct diabatization on each on those structures
/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.0.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.0.log
sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.1.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.1.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.2.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.2.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.3.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.3.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.4.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.4.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.5.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.5.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.6.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.6.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.7.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.7.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.8.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.8.log
#sleep 10
cp /home/$USER/.gamess_ascii_files/$SLURM_JOBID/* .

