#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1       # Number of CPUs
#SBATCH --mem-per-cpu=10G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK
mkdir -p /home/$USER/.gamess_ascii_files/$SLURM_JOBID

# rungms JOB VERNO NCPUS >& JOB.log
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.0.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.0.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.1.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.1.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.2.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.2.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.3.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.3.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.4.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.4.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.5.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.5.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.6.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.6.log
#sleep 10
#/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_3st_diab_as0.7.inp 00 1 &> h2scat_cct_gmcpt_6o7e_3st_diab_as0.7.log
#sleep 10
/home/bjb2chen/gamess/rungms h2scat_cct_gmcpt_6o7e_4st_diab_as0.8.inp 00 1 &> h2scat_cct_gmcpt_6o7e_4st_diab_as0.8.out
sleep 10
cp /home/$USER/.gamess_ascii_files/$SLURM_JOBID/* .
