#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2       # Number of CPUs
#SBATCH --mem-per-cpu=5G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK
mkdir -p /home/$USER/.gamess_ascii_files/$SLURM_JOBID

# rungms JOB VERNO NCPUS >& JOB.log
/home/bjb2chen/gamess/rungms h2ocat_cct_gmcpt_6o7e_C2vinC1_3st.inp 00 2 &> step2_h2ocat_cct_gmcpt_6o7e_C2vinC1_3st.log
