#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4       # Number of CPUs
#SBATCH --mem-per-cpu=7G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK
mkdir -p /home/$USER/.gamess_ascii_files/$SLURM_JOBID

# rungms JOB VERNO NCPUS >& JOB.log
/home/bjb2chen/gamess/rungms h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_diab.inp 00 4 &> step4_h2ocat_cct_gmcpt_6o7e_C2vinC1_3st_diab.log
