#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2       # Number of CPUs
#SBATCH --mem-per-cpu=20G        # memory per CPU in MB

export SLURM_CPUS_PER_TASK
mkdir -p /home/$USER/.gamess_ascii_files/$SLURM_JOBID

# rungms JOB VERNO NCPUS >& JOB.log
/home/bjb2chen/gamess/rungms h2o_cct_mp2_c2v_gh.inp 00 2 &> step1_h2o_cct_mp2_c2v_gh.log
sleep 10
cp /home/$USER/.gamess_ascii_files/$SLURM_JOBID/* .